server:
  port: 80
spring:
  main:
    banner-mode: console
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_db
      username: root
      password: 123456
datasource:
  driver: mysql
  password: 123
  user: root

